### ISSUE TITLE
메인페이지 기본적인 구성

### ISSUE THREAD

**Issue by Februaar** [Februaar/februaar.dev#1]
## ✨ 설명
컴포넌트화 시킬 요소

## ✨ TO-DO
- [x] 메인페이지 헤더 & 푸터
- [x] 키워드 위주로 게시글 리스트 렌더링할 수 있도록 Tag 컴포넌트로 생성해서 페이지 UI 수정
- [x] 게시글 리스트 컴포넌트 최종 정리하기

## ✨ 기타
컴포넌트화 시킬 요소에 대한 기준 세워보기
