### ISSUE TITLE
페이지별로 필요한 컴포넌트 만들기

### ISSUE THREAD

**Issue by Februaar** [Februaar/februaar.dev#3]
## ✨ 설명
체계없이 생각 날 때마다 페이지의 디자인을 구상하고 수정하느라 일관적이지 못하는 것 같아 issue에 기록하고자 함

## ✨ TO-DO
- [x] 메인페지이 tag 컴포넌트
- [x] 메인페이지 postCard 컴포넌트
- [x] 게시글디테일페이지 tag2 컴포넌트

## ✨ 기타
tag 컴포넌트의 동작: onClick => x 버튼이 보이고 배경색 직관적으로 변경, x 버튼을 누르면 비활성화되면서 다시 배경색 변경
postCard 컴포넌트 구성: 게시글 작성 된 날짜와 게시글의 제목 & 내용(미리보기 식)
tag2 컴포넌트 구성: 작성된 게시글에서 중요시 여기는 키워드 직관적으로 보이게 구성
