### ISSUE TITLE
게시글 페이지 데이터 불러오기

### ISSUE THREAD

**Issue by Februaar** [Februaar/februaar.dev#4]
## ✨ 설명
게시글 페이지 기능 추가

## ✨ TO-DO
- [x] 게시글 데이터를 로컬에 폴더로 정리해 저장하고 불러오기
- [x] getPosts 유틸 함수 만들어서 적용하기
- [x] slug 기반 게시글 페이지 동적으로 렌더링
- [x] PostDetailPage 서버 컴포넌트로 리팩 진행

## ✨ 기타
- App Router 환경에서는 useRouter 를 사용하지 않고 generateStaticParams 및 동적 세그먼트를 사용해서 라우팅을 구성할 수 있음
- PostDetailPage에서 서버 전용 함수를 사용하려고 했더니 오류가 발생
 => (오류 해결) PostDetailPage를 서버 컴포넌트로 수정 후 클라이언트 전용 코드는 props로 데이터를 받아 처리하도록 진행하였음
 => MDXRemote를 렌더링하는 부분만 클라이언트 컴포넌트로 별도 생성
