### ISSUE TITLE
게시글 페이지 조건별 렌더링

### ISSUE THREAD

**Issue by Februaar** [Februaar/februaar.dev#8]
## ✨ 설명
연도별로 게시글을 정렬하고 게시글 리스트에 마우스를 hover 했을 때 직관적으로 보이게 css 적용하고싶음!

## ✨ TO-DO
- [x] 게시글 연도별 그룹화하는 유틸 함수 만들기
- [x] /posts 에서는 [mm.dd] 형식으로만 보이게 수정
- [x] 게시글 아이템에 transition 효과 주기 

## ✨ 기타
- 기본적인 메서드 정리해두고 익히기
=> split(), slice(), join()
